name: astro_people
description: The flutter developer assignment
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  #analyzer: ^1.0.0
  bloc: ^8.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  google_fonts: ^2.3.1
  intl: ^0.17.0
  rest_api_manager:
    path: modules/rest_api_manager

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/media/images/
