name: rest_api_manager
description: To manage rest api request easily
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  very_good_analysis: ^2.4.0